export const testEmails = [
  // Original 50
  "Hi, I was looking at one of your products and was wondering how much shipping costs. I couldn't find the information on the product page. Thanks!",
  "Hello, I'm located in Canada and I'm interested in ordering from your shop. Do you ship internationally, and if so, what countries do you ship to? Thank you.",
  "Hi there, I placed an order a few days ago and was just wondering when I should expect it to arrive. I need it for an upcoming event. Thanks!",
  "Hello, My tracking information hasn't updated in several days. It looks like my package is delayed. Can you tell me what's going on? Thank you.",
  "Hi, I just placed an order this morning and realized I need it sooner than expected. Is it possible to upgrade to expedited shipping? Thanks.",
  "Hello, Before placing an order, I wanted to ask if you offer free shipping on larger purchases or during promotions. Best regards.",
  "Hi, I placed an order recently and wanted to check whether it has shipped yet. I haven't received any updates so far. Thank you.",
  "Hello, My order confirmation came through, but I never received a tracking number. Could you send it to me when you get a chance? Thanks.",
  "Hi, The tracking information for my order has been stuck on the same status for several days. Is this normal, or should I be concerned? Thanks for your help.",
  "Hello, I received my package today, but one of the items I ordered wasn't included. Can you help me figure out what happened? Thank you.",
  "Hi, I recently received my order, but it's not quite what I expected. I'd like to know if returns are accepted and what the process is. Thanks.",
  "Hello, Before I make a purchase, I wanted to understand your refund policy. How are refunds handled if there is an issue with an order? Thank you.",
  "Hi, I was told my refund had been processed, but I still haven't seen it appear in my account. Could you provide an update? Thanks.",
  "Hello, The item I received is the wrong size. Is it possible to exchange it for a different size instead of returning it? Thank you.",
  "Hi, I accidentally ordered the wrong version of your product. Is there any way to change it before it ships? Sorry about that!",
  "Hello, Unfortunately, my order arrived damaged. The product was broken when I opened the package. I've attached photos for reference. Please let me know what can be done. Thank you.",
  "Hi, The shipping box arrived crushed and damaged. I'm worried the product inside may have been affected. What should I do next? Thanks.",
  "Hello, I've only used the product once, and it doesn't seem to be working properly. It appears to have a defect. Can you help me with a replacement or refund? Thank you.",
  "Hi, I received my order today, but it looks quite different from the photos shown online. Can you clarify whether I received the correct item? Thanks.",
  "Hello, My package arrived, but one of the accessories that was supposed to be included wasn't in the box. Could you check this for me? Thank you.",
  "Hi, I really like this item, but I was wondering if you offer any customization options. I'd love something a little more personalized. Thanks!",
  "Hello, I'd like to order this item as a gift. Is it possible to add a name or custom text to it? Thank you.",
  "Hi, I love the design, but I was hoping to get it in a different color. Is that something you can accommodate? Thanks.",
  "Hello, The product looks perfect, but I need a larger size than what's currently listed. Is a custom size available? Thank you.",
  "Hi, I need this item for a birthday next week. If I place my order today, would it be possible to rush production and shipping? I'd really appreciate it.",
  "Hello, I'm interested in purchasing this item, but I'd like to know what materials it's made from. I have some allergies and want to make sure it will be suitable for me. Thank you.",
  "Hi, Could you tell me the exact dimensions of this product? I'm trying to figure out if it will fit in a specific space before ordering. Thanks!",
  "Hello, I was wondering if this item is waterproof or water-resistant. I'd like to use it outdoors occasionally and wanted to check before purchasing. Thank you.",
  "Hi, I'm considering buying this as a gift for my child. Is it safe for young children, and are there any small parts I should be aware of? Thanks.",
  "Hello, I really like this product, but I'd love to see a few more photos from different angles before making a decision. Thank you.",
  "Hi, I'm interested in ordering this item but wanted to make sure it's currently in stock. Could you let me know? Thanks!",
  "Hello, I noticed the item I wanted is sold out. Do you have an estimate for when it will be available again? Thank you.",
  "Hi, I saw that stock seems limited. Would it be possible to reserve one for me until I'm ready to place my order later this week? Thanks.",
  "Hello, I really like this product, but I'm looking for a different color option. Do you happen to offer any other colors? Thank you.",
  "Hi, I'm planning to place an order soon and was wondering if you currently have any discounts or promotions available. Thanks!",
  "Hello, I'm interested in purchasing about 20 units for an event. Do you offer discounts on larger orders? Thank you.",
  "Hi, I was about to complete my order but noticed the shipping cost is quite high. Could you explain why shipping is priced this way? Thanks.",
  "Hello, Before placing my order, I thought I'd ask if there are any coupon codes or promotions available right now. Thank you.",
  "Hi, I wanted to know your business hours in case I need assistance with my order. When is your support team available? Thanks.",
  "Hello, What's the best way to get in touch with customer support if I have questions after placing an order? Thank you.",
  "Hi, I'm curious where your business is based. I like supporting small businesses and wanted to learn a little more about your company. Thanks!",
  "Hello, I received my order yesterday, and unfortunately I'm not satisfied with it. It didn't meet my expectations based on the product description. I'd appreciate any help you can offer. Thank you.",
  "Hi, I sent a message several days ago and haven't received a response yet. I'm starting to get concerned because I need help with my order. Please get back to me as soon as possible. Thank you.",
  "Hello, I wanted to share that my experience with this order has been disappointing. Between the delays and communication issues, I'm frustrated with how things have gone. I'd like to discuss possible solutions. Thank you.",
  "Hi, I just wanted to say thank you for helping me with my recent order. Your quick response and assistance made everything much easier. I really appreciate it!",
  "Hello, My package arrived today, and I absolutely love it! The quality exceeded my expectations, and I couldn't be happier with my purchase. Thank you so much!",
  "Hi, I had such a great experience with my recent order that I wanted to let you know I'll definitely be coming back for more in the future. Keep up the great work!",
  "Hello, I recently placed an order, but my plans have changed. Is it still possible to cancel it before it ships? Thank you.",
  "Hi, I just realized I entered the wrong shipping address during checkout. Could you update it before the order is shipped? Thanks for your help.",
  "Hello, I'm purchasing this item as a gift and was wondering whether you offer gift wrapping or gift messages. Thank you.",

  // New 150
  "Hi, My order was supposed to arrive three days ago, but the tracking hasn't updated. Can you check on it? Thanks.",
  "Hello, I ordered a medium blue hoodie and received a large black one. Please advise on how to exchange it. Thank you.",
  "Hi, I received my package today, but one of the items listed on the packing slip wasn't in the box. Order #58214. Thanks.",
  "Just wanted to say I'm very happy with my purchase. The quality is excellent and shipping was fast.",
  "Hello, I returned an item last week and wanted to know when I should expect my refund. Regards, Sarah",
  "Hi, The tracking says delivered, but nothing has arrived at my house. Could you help me figure out what happened?",
  "Hello, I'm thinking about ordering your jacket. Does it run small, large, or true to size? Thank you.",
  "Hi, I accidentally entered the wrong shipping address. Is it possible to update it before the order ships? Thanks.",
  "Hello, The item arrived with a crack in it. I've attached photos. Please let me know what can be done. Thank you.",
  "Hi, I just placed an order about an hour ago and would like to cancel it if possible. Thanks.",
  "Hello, The coupon code from your newsletter doesn't seem to work during checkout. Can you help?",
  "Hi, Is this item waterproof? I couldn't find that information on the product page. Thanks.",
  "I paid for express shipping and my order still hasn't arrived. This is very frustrating.",
  "Hello, Could you send me a return shipping label? Thank you.",
  "Hi, I wanted to thank your support team for helping me with my order. The experience was excellent.",
  "hey, tracking has been stuck for 4 days. is this normal?",
  "Hello, I'd like to exchange my item for a different size. What steps should I follow? Thanks.",
  "Hi, This is a gift. Do your packages include pricing information? Thank you.",
  "Hello, The product I received appears to have scratches and signs of previous use. Was I sent a returned item? Regards.",
  "Hi, If I order today, when would it likely arrive in Texas? Thanks.",
  "Hello, I keep getting an error when trying to sign into my account. Can someone assist? Thank you.",
  "Hi, I ordered 3 units but only received 2. Order #83492.",
  "Everything arrived perfectly. I'll definitely be ordering again.",
  "Hello, Could you send me a copy of my invoice for accounting purposes? Thank you.",
  "Hi, The package eventually arrived, but much later than expected. Is shipping usually this slow?",
  "Hello, The item stopped working after only two days. I'd like a replacement. Thanks.",
  "Hi, Will this item be back in stock soon? Thank you.",
  "Hello, My order has been in processing status for nearly a week. Is there a delay? Regards.",
  "Hi, I accidentally ordered the wrong size and need to fix it before shipment. Please help.",
  "hello, the box arrived crushed. product seems okay but i wanted to report it.",
  "Hi, Do you ship to Canada? If so, what are the shipping costs? Thank you.",
  "Hello, I was told my refund was processed 10 business days ago, but I still haven't received it. Thanks.",
  "Hi, I'm deciding between two products on your website. Which would you recommend for a beginner? Thank you.",
  "Hello, I placed an order but never received a confirmation email. Can you verify if the order went through?",
  "Hi, The quality exceeded my expectations. Thank you for making such a great product.",
  "Hello, The zipper broke the first time I used the item. What are my options?",
  "Hi, Can I upgrade my shipping method after placing the order? Thanks.",
  "Hello, I noticed a charge that doesn't match my order total. Could you explain?",
  "Hi, I ordered this as a birthday present, but it didn't arrive in time. Very disappointed.",
  "Hello, Could you provide the exact dimensions of this item? Thank you.",
  "Hi, My gift card code isn't being accepted at checkout. Can you assist?",
  "Hello, You approved a replacement shipment last week. Has it been sent yet? Thanks.",
  "Hi, The packaging was beautiful and everything arrived safely. Great job.",
  "Hello, I accidentally submitted the same order twice. Can one of them be canceled? Thank you.",
  "Hi, I haven't heard anything since placing my order six days ago. Can you provide an update?",
  "hello, the item is way too small. can i exchange it?",
  "Hi, Is the color shown in the photos accurate in real life? Thanks.",
  "Hello, My order shipped, but I never received tracking information. Could you resend it?",
  "Everything went smoothly. Fast shipping, great product, and excellent communication. Thank you.",
  "Hello, I'm having trouble deciding which product best fits my needs. Could someone provide guidance? Thank you.",
  "Hi, I just realized my order was shipped to my old address. Is there anything that can be done? Thanks.",
  "Hello, My order arrived today and everything looks fantastic. Thank you for the great experience.",
  "Hi, The product appears to have dirt or marks on it right out of the box. Can I exchange it? Thank you.",
  "Hello, Why is the shipping cost so high for a small item? Regards.",
  "Hi, How long do I have to return an item after receiving it? Thanks.",
  "Hello, Tracking stopped updating two weeks ago and the package still hasn't arrived. Can you help?",
  "Hi, I'm sending this as a gift. Is it possible to include a gift receipt instead of the normal invoice? Thank you.",
  "Hello, What is the difference between Model A and Model B? They look very similar. Thanks.",
  "Hi, The package arrived but one of the accessories shown in the listing was missing. Please advise.",
  "Just wanted to say your customer service team was incredibly helpful. I really appreciate it.",
  "hey, i think someone else's order got sent to me. none of these items are what i bought.",
  "Hello, My tracking page shows a shipping exception. What does that mean? Thanks.",
  "Hi, I used the product once and it already stopped working. Could I get a replacement?",
  "Hello, I was charged, but I never received an order confirmation email. Thank you.",
  "Hi, I'm buying this for my son and I'm not sure which option is best. Could you help me choose?",
  "This is the third time I've contacted support and I still haven't received an answer. Please respond.",
  "Hello, I received two of the same item, but I only ordered one. What should I do?",
  "Hi, Will I need to pay customs fees for international shipping? Thanks.",
  "Hello, The outer box was badly damaged during transit. Fortunately the item seems okay. Just wanted to let you know.",
  "Hi, I lost one of the included pieces. Is it possible to purchase a replacement part? Thank you.",
  "Everything from ordering to delivery went perfectly. I'll definitely recommend your store.",
  "Hello, I ordered a medium but need a large. Can I exchange it? Thanks.",
  "Hi, My coupon expired yesterday. Is there any chance it can still be honored? Thank you.",
  "Hello, The product has several scratches on it. I've attached photos. Please advise.",
  "Hi, Can you tell me if there are any delays affecting my shipment? Thanks.",
  "Hello, Does this product require assembly when it arrives? Thank you.",
  "Hi, I received an email saying my refund was completed, but the money isn't in my account. Could you check?",
  "Hello, The checkout page freezes every time I try to place an order. Thanks.",
  "Hi, I was surprised to receive my package earlier than expected. Great service!",
  "Hello, The size chart seems inaccurate. The item I received is much smaller than expected. Regards.",
  "Hi, Could you send me a copy of my order details? Thanks.",
  "Hello, The color looks very different from the photos on the website. Can I return it?",
  "Hi, Can this item be used outdoors? Thank you.",
  "I had an issue with my order and your team resolved it quickly. Thank you very much.",
  "Hello, I selected express shipping but my confirmation email shows standard shipping. Can this be corrected?",
  "hi, tracking says delivered but nothing showed up. checked with neighbors too.",
  "Hello, The product I received does not match the description on your website. Please advise.",
  "Hi, I'm interested in ordering 50 units. Do you offer bulk discounts? Thanks.",
  "Hello, I have an upcoming event. Is there any way to speed up my shipment? Thank you.",
  "Hi, The item was broken when I opened the package. Can I get a replacement?",
  "Hello, Do you offer rewards or loyalty points for repeat customers? Thanks.",
  "Hi, I've ordered from many companies before, and this is one of the best products I've received.",
  "Hello, I entered the wrong billing address during checkout. Will this cause a problem?",
  "Hi, I shipped my return back a few days ago. Have you received it yet? Thanks.",
  "Hello, The product arrived without the instruction booklet. Can you send a digital copy?",
  "i paid a lot of money for this and expected better quality. really disappointed.",
  "Hello, Will this item work with the previous version I purchased last year? Thank you.",
  "Hi, Every time I try to complete my order I receive an error message. Can someone help?",
  "Everything was exactly as described and arrived quickly. Thank you!",
  "Hello, I placed my order over a week ago and would appreciate an update on its status. Thank you.",
  "Hello, My tracking hasn't updated in 9 days. I'm starting to worry the package may be lost. Could you investigate? Thank you.",
  "Hi, I rarely write reviews or emails, but I wanted to let you know that your service was outstanding. Everything arrived perfectly. Thanks!",
  "Hello, I accidentally selected the wrong product variant. Is it possible to change it before shipment? Regards.",
  "Hi, The item arrived today, but it has a strong odor. Is that normal? Thank you.",
  "Hello, Do you ship to Alaska, and if so, how long does delivery usually take? Thanks.",
  "Hi, I ordered four units but only received three. Order #91382. Please advise.",
  "Hello, I've decided I no longer need the item and would like to request a refund. Thank you.",
  "Hi, The quality is nowhere near what I expected based on the photos and description. I would like to discuss return options.",
  "Hello, Could you provide an update on order #76125? Thanks.",
  "Just wanted to say thank you. The product is great and arrived sooner than expected.",
  "Hello, The package arrived with several holes in the box. Luckily the item seems okay. Thought you should know.",
  "Hi, The tracking link in my email doesn't open correctly. Can you send another one?",
  "Hello, The item fits, but it's tighter than I'd like. Can I exchange it for the next size up? Thanks.",
  "Hi, Is the navy blue version darker than it appears in the photos? Thank you.",
  "Hello, I've never returned an item before. Could you explain the process? Regards.",
  "Hi, The package finally arrived today, but it was over a week later than the estimate. Thanks.",
  "Hello, When I try to add an item to my cart, the page refreshes and removes it. Can someone look into this?",
  "Hi, Could you send my invoice today? I need it for expense reporting. Thank you.",
  "Hello, This was my first order from your store and I'm very impressed. I'll definitely be back.",
  "Hi, The main product arrived, but one of the included accessories wasn't in the box. Please help.",
  "hello, it worked for about 10 minutes and then stopped completely. what should i do?",
  "Hi, My order hasn't shipped yet. Can I pay extra to upgrade shipping speed? Thanks.",
  "Hello, I'm shopping for a gift and don't know which model would be best. Could you make a recommendation?",
  "Hi, I ordered a large but received a medium. Order #48261. Thank you.",
  "Hello, Everything was packaged extremely well and arrived in perfect condition. Great work.",
  "Hi, I just received a notification saying my order was canceled, but I didn't request that. Can you explain?",
  "Hello, Do customers pay for return shipping, or is a prepaid label provided? Thank you.",
  "Hi, I've been checking for weeks. Any idea when this item will be back in stock? Thanks.",
  "Hello, I've contacted support twice already and haven't heard back. I need assistance with my order. Please respond.",
  "Hi, There were fingerprints and dust on the product when I opened the package. Can it be exchanged?",
  "Hello, I accidentally misspelled my street name during checkout. Will the package still arrive? Thanks.",
  "Hi, Your team helped solve my issue quickly and professionally. I really appreciate it.",
  "Hello, Could you provide the exact measurements of the item before I order? Thank you.",
  "Hi, The website keeps saying my payment failed, but my bank says everything is fine. Can you help?",
  "Hello, My package arrived today, but the box was empty except for packing material. Please advise immediately.",
  "Hi, Everything was perfect from start to finish. Fast shipping and excellent quality.",
  "Hello, Can I exchange an item if I've already opened the packaging? Thanks.",
  "Hi, This is for an event on Friday. Based on current processing times, do you think it will arrive in time? Thank you.",
  "Hello, The product I received is completely different from what I ordered. Please help resolve this.",
  "hi, this is the second delivery delay notification i've received. what's going on?",
  "Hello, Can you tell me how to check the remaining balance on my gift card? Thanks.",
  "Hi, The replacement item arrived today and works perfectly. Thank you for handling the issue.",
  "Hello, What materials are used to make this product? Thank you.",
  "Hi, My order status says shipped, but I never received a shipping email. Could you resend it?",
  "Hello, The item broke after only a few days of normal use. I'd like to know what warranty options are available.",
  "Hi, Could you provide a receipt showing the taxes paid on my order? Thank you.",
  "Hello, The craftsmanship is excellent. I'm genuinely impressed with the attention to detail.",
  "Hi, I seem to be locked out of my account after entering my password incorrectly. Can someone assist?",
  "Hello, I submitted a return request a few days ago and wanted to check whether it has been approved. Thank you.",
  "Hi, I've placed several orders over the past year and wanted to share some positive feedback. The products have consistently been high quality, shipping is usually fast, and your support team has always been helpful when I've needed assistance. Thank you for the great service."
];